version: '3.8'

services:
  telegram_bot:
    build:
      context: .
      dockerfile: docker/telegram_bot/Dockerfile.prod
    container_name: telegram_bot
    env_file:
      - .env
    ports:
      - "${TELEGRAM_PORT}:${TELEGRAM_PORT}"
    volumes:
      - .:/telegram_bot
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://telegram_bot:${TELEGRAM_PORT}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  http_server:
    build:
      context: .
      dockerfile: docker/http_server/Dockerfile.prod
    container_name: http_server
    env_file:
      - .env
    ports:
      - "${HTTP_PORT}:${HTTP_PORT}"
    volumes:
      - .:/http_server
    depends_on:
      - mongo
    restart: unless-stopped
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://http_server:${HTTP_PORT}" ]
      interval: 30s
      timeout: 10s
      retries: 3

  mongo:
    image: mongo:latest
    container_name: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - "${MONGO_PORT}:${MONGO_PORT}"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: [ "CMD", "mongo", "--eval", "db.adminCommand('ping')" ]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx
    container_name: nginx
    volumes:
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/conf/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/cert/${DOMAIN}/fullchain.pem:/etc/nginx/fullchain.pem
      - ./docker/nginx/cert/${DOMAIN}/privkey.pem:/etc/nginx/privkey.pem
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      telegram_bot:
        condition: service_healthy
      http_server:
        condition: service_healthy
    restart: unless-stopped

volumes:
  mongo_data:
