version: '3.8'

services:
  event_manager_bot:
    build:
      context: .
      dockerfile: docker/telegram_bot/Dockerfile.prod

  event_manager_server:
    build:
      context: .
      dockerfile: docker/http_server/Dockerfile.prod
